# Generated by Django 5.1 on 2024-08-23 06:16

import cat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_item_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=cat.models.upload_to),
        ),
    ]
